# // docker-compose.yml
services:
 
# // backend section of docker-compose.yml
 

  db:
    image: postgres:15-alpine
    pull_policy: if_not_present
    ports:
      - "5432:5432"
    networks:
      - private_net
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: code_db
    volumes:
      - pgdata:/var/lib/postgresql/data



 
networks:
  public_net:
  private_net:

volumes:
  pgdata: